### ISSUE TITLE
auto open some site in private tab

### ISSUE THREAD

**Issue by ivysrono** [Infocatcher/Private_Tab#100]
for example，auto change to private tab when I open the www.aaa.com 

and it is best that  if the site rules could be subscribed just like adblock plus

**Comment by anewuser** [comment]
@Infocatcher Does this extension works as expected for you? I had to add \*translate.google.com\* to the list for it to work. Without the asterisks, nothing happens.

**Comment by Infocatcher** [comment]
Similar (but opposite) request: #170

**Comment by anewuser** [comment]
@Infocatcher after using Auto Private to open search engine results in private tabs for two days, I'm dealing with very high memory usage. Please consider again adding your own implementation of it to Private Tab. You're a much more experienced developer, and that guy doesn't seem to care enough about his project.

**Comment by anewuser** [comment]
@ivysrono https://addons.mozilla.org/addon/temporary-containers/
