### ISSUE TITLE
Spell Check Does Not Work

### ISSUE THREAD

**Issue by LackLuster** [Infocatcher/Private_Tab#139]
Spell check doesn't seem to work with this extension. Is this something that will be fixed, or does the user just have to work around it? Only reason I ask is because I rather enjoy the in browser spell check option of Firefox. I do love this extension though. It should be a main Firefox feature.

(This is on Firefox 28)

**Comment by anewuser** [comment]
It still works fine on Firefox 48. Since the creator of the issue never came back, you can close this.

**Comment by Infocatcher** [comment]
> It still works fine on Firefox 48. Since the creator of the issue never came back, you can close this.

Oh, yes. :)
Looks like this is something caused by another extension (and there is only one report for 2 years).
