### ISSUE TITLE
New York Times FREE - works in private window, not private tab

### ISSUE THREAD

**Issue by sirald66** [Infocatcher/Private_Tab#155]
HP G72 253NR
WIN 7HP x64 SP1
FIREFOX 31.0  (new profile)
TAB 0.1.7.3
http://www.nytimes.com/2014/08/20/us/texas-gov-rick-perry-enlists-help-of-high-profile-lawyers.html

PrivateTab does **not** prevent NYT from detecting your unique browser profile after reading your 10 free monthly news article links.

But a private-window **does** prevent NYT from detecting your unique browser.

**Comment by anewuser** [comment]
Since OP never provided more information, and we can't reproduce it, this issue may be closed.

**Comment by Infocatcher** [comment]
> Since OP never provided more information, and we can't reproduce it, this issue may be closed.

Oh, yes, looks obsolete.
