### ISSUE TITLE
Broken in version 31.4.0

### ISSUE THREAD

**Issue by davidhedlund** [Infocatcher/Private_Tab#167]
I do not see it when I use browser version 31.4.0. Can you have a look?

I tried Private Tab 0.1.7.3

**Comment by Infocatcher** [comment]
Hmm... works fine for me.
There is toolbar button in about:customizing tab, context menu items for links, bookmarks and tabs...

**Comment by davidhedlund** [comment]
@Infocatcher I can see it now, using Private Tab 0.1.7.5.
