### ISSUE TITLE
Make middle-click on private tab button open new homepage via private tab

### ISSUE THREAD

**Issue by joesimmons** [Infocatcher/Private_Tab#169]
It seems like middle-clicking on the *New Private Tab* button has the same effect as the regular *New Tab* button, so I thought it would be useful for that action to do something different. It would make sense to open the most recently closed tab as a private tab, but that doesn't seem that useful.

I think it would be more useful if middle-clicking the private tab button would open a new private homepage tab. There are many times where I want to open a new private tab of my homepage, but I always have to perform at least 2 actions to get there.

Would like your thoughts, no rush.

Cheers :)

**Comment by Infocatcher** [comment]
Currently middle-click on `New Private Tab` button is used to open new private tab right after current tab (or in child tab, if installed <a href="https://addons.mozilla.org/firefox/addon/tree-style-tab/">Tree Style Tab</a>).

See https://github.com/Infocatcher/Private_Tab/issues/117

**Comment by joesimmons** [comment]
But it does the same exact thing as the new tab button (opens most recently closed tab, not even privately).

**Comment by Infocatcher** [comment]
> But it does the same exact thing as the new tab button (opens most recently closed tab, not even privately).

Strange... may be caused by some another extension.

**Comment by joesimmons** [comment]
Ya, I think you're right. Whatever I've changed, middle-clicking the new tab now opens a new tab, and the private tab button opens a new private tab. I'll close this. Thanks for the replies.
