### ISSUE TITLE
Allow links to open in normal tab

### ISSUE THREAD

**Issue by czardoz** [Infocatcher/Private_Tab#171]
Currently, any link opened in a Private tab opens a new Private Tab. If I am logged into say my Google account, and click on a search link, Google saves that search, because I am still logged into the Google account (in the Private Tab). 

There should be an option to open a link in a new normal tab.

**Comment by Infocatcher** [comment]
This is "by design": to not leak private things by mistake.
Anyway, you can copy link and open in non-private tab or use "Private Tab" checkbox in tab context menu.

**Comment by czardoz** [comment]
Makes sense about not accidentally leaking private data. What bugs me is, if I log in to Google in a private tab, and say I highlight a phrase in an email and Select -> RightClick -> Search, the history gets recorded in my Google account (since I think all the private tabs share cookies across them. I am not too sure about this though). Any way to avoid that?

**Comment by czardoz** [comment]
Okay after reading a bit more about this, it looks like all Private Tabs share the same Firefox "profile". Is there a way of creating a separate profile per tab? I wouldn't mind working on a PR, if you can give me a bit of a nudge in the right direction.

**Comment by Infocatcher** [comment]
> since I think all the private tabs share cookies across them.

Yes, there is only two (and built-in) "profiles": one for non-private things and one for private ones. And it's very difficult to change this into per-tab basis.

And also possible something like with <a href="https://addons.mozilla.org/firefox/addon/multifox/">Multifox</a> extension.
