### ISSUE TITLE
Wrong/Useless private tab message in non-private tab

### ISSUE THREAD

**Issue by rugk** [Infocatcher/Private_Tab#177]
Right after your last update this issue occured.

Steps to reproduce:
1. Open a new normal window. (e.g. by dragging and dropping a tab out of the actual window)
2. Open a **normal** (=non-private) tab as you normally would.
3. The issue occurs. Firefox doesn't display about:newtab correctly, but it shows this (quite useless) message:
![privatetab_wrongprivatetabmessage](https://cloud.githubusercontent.com/assets/11966684/7735926/b9eaf922-ff40-11e4-95c6-1da20cfdccb3.PNG)

There it states "correctly" that the tab is *not* a private window, but prompts to open a private window.
BTW exactly the same message is also displayed for private tabs, so that's strange too.

Windows 7
Firefox 38.0.1
Plugin Version: 0.1.7.4

**Comment by Infocatcher** [comment]
Looks like I found a reason: 29c43a5ed62bce0b6cd9814bf2606717f27f79e8

**Comment by rugk** [comment]
Okay, great. :+1:

**Comment by Infocatcher** [comment]
Oh, to be really sure... Please try test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.1.7.6pre-fx-sm.xpi">private_tab-0.1.7.6pre-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/29c43a5ed62bce0b6cd9814bf2606717f27f79e8">source code</a>).

**Comment by Rikk** [comment]
Oh long time having this bug, never figured out what plugin was causing it.

For some time I used `layers.offmainthreadcomposition.enabled = false` as workaround, but was not worth due to some other quirks.

That test version looks good, thanks!

**Comment by rugk** [comment]
I can confirm that it's fixed with the version you provided. (fixed by 29c43a5ed62bce0b6cd9814bf2606717f27f79e8)
