### ISSUE TITLE
Hide icon on tab toolbar

### ISSUE THREAD

**Issue by dachacha** [Infocatcher/Private_Tab#179]
Greetings!
First of all thanks for the great addon! It really helps keep browsing history clean.
I have a little suggestion - add an option(through about:config) to hide this > http://i.imgur.com/7gFPn8o.png
It shifts tabs a bit when switching between private and non-private tabs and that's a bit annoying.
Thanks!

**Comment by Infocatcher** [comment]
You can set _extensions.privateTab.usePrivateWindowStyle_ = false to disable that appearance (and all other possible styles for built-in private window).

**Comment by dachacha** [comment]
Just what I need. Thank you once again!

**Comment by anewuser** [comment]
@Infocatcher Maybe you could add this piece of info to the frontpage of the project.

**Comment by Infocatcher** [comment]
> Maybe you could add this piece of info to the Readme file of the project. I had never hidden that icon before on Windows, but now that I'm using Linux I was looking up how to do that because the Linux version of Firefox displays the icon on the left instead of the right of the tab bar.

Done: 1148b32dfa56fca93136a2c5424000f4f5c23867
https://github.com/Infocatcher/Private_Tab#options
