### ISSUE TITLE
Open Link in New Private Tab Broken [Ffx 41] [OSX] [E10s]

### ISSUE THREAD

**Issue by theHokage** [Infocatcher/Private_Tab#181]
Right Click > Open in New Private Tab is broken in Nightly. Possible e10s issue. Currently request simply fails.

**Comment by Infocatcher** [comment]
Yes, many things are broken with enabled e10s: #162
This caused by the same reason as #182: content process doesn't initialized yet at tab opening state.

**Comment by theHokage** [comment]
Interesting. I assumed this issue - #181, was due to e10s, but since the new private tab shortcut works in windows, I figured #182 had a good chance of not being due to e10s. My bad!

**Comment by Infocatcher** [comment]
Most of e10s-related bugs (include this one) should be fixed in latest version:
https://addons.mozilla.org/addon/private-tab/versions/0.2.0
