### ISSUE TITLE
Putting "New Private Tab" button next to "New Tab" button turns both icons invisible

### ISSUE THREAD

**Issue by DawnPaladin** [Infocatcher/Private_Tab#185]
I like to put my "New Private Tab" button next to my New Tab icon. For a long time, this has worked really well. However, as of Firefox 40, putting that button there causes both icons to become invisible. 

![capture](https://cloud.githubusercontent.com/assets/5524469/9201347/22aac32c-4012-11e5-8899-9cce1bddbb4e.PNG)

![new-tab](https://cloud.githubusercontent.com/assets/5524469/9201591/71fa5144-4013-11e5-8bcf-6520479919fc.png)

![new-private-tab](https://cloud.githubusercontent.com/assets/5524469/9201602/78fc5a82-4013-11e5-8b5c-30863d7daa78.png)

I can confirm that this is caused by Firefox 40--I was actually writing up some documentation on how to set this up, upgraded from 39 to 40, and the procedure no longer worked.

I've tried hitting "Restore Defaults" on the Customize screen, and having a friend try the same procedure on a relatively fresh installation of Firefox.

**Comment by Infocatcher** [comment]
See #180.
I hope to release that fix soon...
