### ISSUE TITLE
Issue with HD displays

### ISSUE THREAD

**Issue by belaviyo** [Infocatcher/Private_Tab#188]
Hi,
Can this bug be fixed?
<img width="161" alt="screen shot 2015-08-30 at 16 19 16" src="https://cloud.githubusercontent.com/assets/1221138/9567077/1b29b6f0-4f33-11e5-92e0-9cdee4d48e25.png">
If I remove the private tab, the new tab button icon size will be fixed. I have tested this in a clean profile. It occurs in Mac OS. Apparently, the new "new tab" button supports HD resolution.

**Comment by Infocatcher** [comment]
May be this is yet another side-effect for enabled _extensions.privateTab.fixAfterTabsButtonsAccessibility_ in about:config (also see #183).
Buttons looks squared (and without Australis edges), so this fix may be not needed.

**Comment by belaviyo** [comment]
Changing the pref fixed the problem. Thanks
