### ISSUE TITLE
Opening a link from an external application is not in the private mode even when the currently selected tab is private

### ISSUE THREAD

**Issue by belaviyo** [Infocatcher/Private_Tab#189]
"Private Tab" used to open a new tab (sent from an external application) in the private mode when the currently active tab was in the private mode. But in FF 40 & 41, this is not working anymore. If I click on a link from for instance my Thunderbird, the link is opened in the normal mode, not private mode anymore.

**Comment by Infocatcher** [comment]
This is expected behavior and was fixed in recent update: #184
You should set _extensions.privateTab.allowOpenExternalLinksInPrivateTabs_ = true in about:config.

**Comment by belaviyo** [comment]
Thanks
