### ISSUE TITLE
Firefox Firefox 42.0b9 broke "private:" pseudo-protocol

### ISSUE THREAD

**Issue by anewuser** [Infocatcher/Private_Tab#190]
Private Tab 0.1.8 was working fine for me until the [Firefox 42 Beta 9 update](https://www.mozilla.org/en-US/firefox/channel/#beta), but this doesn't work anymore:

    private:https://example.org

I installed Private Tab 0.1.8.1 [from this page](https://addons.mozilla.org/en-US/firefox/addon/private-tab/versions/), but it still doesn't work.

This has been reported to Mozilla, but they usually tell us to report such problems to the extension developers instead. If you can't fix it, please provide the necessary technical info for them here: https://bugzilla.mozilla.org/show_bug.cgi?id=1218143

**Comment by Infocatcher** [comment]
Most likely this is due to enabled multiprocess mode, see https://bugzilla.mozilla.org/show_bug.cgi?id=1114946#c7
Also something may be fixed here https://bugzilla.mozilla.org/show_bug.cgi?id=1095484 (I hope...)

**Comment by anewuser** [comment]
No, even if multiprocess is enabled by default now, I have it turned off:

![untitled-1](https://cloud.githubusercontent.com/assets/6733770/10715286/6dd5f698-7af8-11e5-9e8f-2833412c40b1.png)

**Comment by Infocatcher** [comment]
Oops, now I see. All was fine in Firefox 42.0b8.

Also interesting:
42.0b8 - Ok
42.0b9 - broken
43.0a2 (2015-10-22) - broken
43.0a2 (2015-10-25) - Ok
44.0a1 (2015-10-23) - Ok
44.0a1 (2015-10-25) - Ok

**Comment by anewuser** [comment]
This has been fixed on https://ftp.mozilla.org/pub/firefox/releases/42.0/win64/

**Comment by Infocatcher** [comment]
> This has been fixed on https://ftp.mozilla.org/pub/firefox/releases/42.0/win64/

Great! Thanks for testing.
