### ISSUE TITLE
Extension page on the Firefox Add-ons Manager has a link to the SeaMonkey URL

### ISSUE THREAD

**Issue by anewuser** [Infocatcher/Private_Tab#191]
Even if it's the same .xpi file, this may be confusing for Firefox users who click on it.

![untitled-1](https://cloud.githubusercontent.com/assets/6733770/10715831/7bb399e2-7b0b-11e5-8527-dc500f3bd711.png)

I suggest you to replace it with https://addons.mozilla.org/addon/private-tab/ , with the browser and language strings removed, so it goes to the Mozilla site with the user's own system language and hopefully browser too. I've just tested it on Firefox.

**Comment by Infocatcher** [comment]
Strange, homepage isn't <a href="https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#homepageURL">hardcoded in the sources</a> and comes from Firefox add-on manager.
For me appears correct https://addons.mozilla.org/ru/firefox/addon/private-tab/?src=api (for Russian locale).

**Comment by anewuser** [comment]
I really don't know what caused this to my main Firefox profile then. After your comment, I thought that maybe I was the one who installed the extension from the SeaMonkey page (https://addons.mozilla.org/en-US/seamonkey/addon/private-tab/), and Firefox set that as its souce URL and didn't change it even after I updated Private Tab manually. 

However, I just use that SeaMonkey link to install Private Tab on a fresh profile of Firefox, and the link on the Add-ons Manager is the correct Firefox one (similar to yours).
