### ISSUE TITLE
Firefox 42 removes keywords from bookmarks with %s and private:

### ISSUE THREAD

**Issue by anewuser** [Infocatcher/Private_Tab#195]
I have many bookmarks with keywords on Firefox which act as "custom search engines" or ways to quickly access arbitrary pages of a website. For example, I have this dictionary bookmark:

    URL: private:http://wordreference.com/enru/%s
    keyword: enru

When I type `enru example` into the address bar, it goes to `private:http://wordreference.com/enru/example`.

This worked fine until today. I edited one of those bookmarks and Firefox 42 automatically removed the keyword. It will keep removing it until I drop `private:` from the URL. I've deleted my entire Firefox places.sqlite file (which stores history+bookmarks) and manually re-added my search engines, but the problem persists.

Can you please confirm this problem? It doesn't seem to happen to bookmarks without the `%s` parameter. You can create a custom search engine like mine on the Library (`chrome://browser/content/places/places.xul`). Click on a bookmark and then on "More" at the bottom of the window.

**Comment by anewuser** [comment]
I've reported this on Bugzilla too: https://bugzilla.mozilla.org/show_bug.cgi?id=1228004

**Comment by Infocatcher** [comment]
> I edited one of those bookmarks and Firefox 42 automatically removed the keyword. It will keep removing it until I drop `private:` from the URL.

Interesting... As I see, keyword may also disappears, if URL was edited somehow (after any modification, not only around protocol part).

**Comment by anewuser** [comment]
This won't be fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1285142#c8
