### ISSUE TITLE
Conflict with another extension: list of closed tabs may become broken

### ISSUE THREAD

**Issue by sdavidg** [Infocatcher/Private_Tab#197]
1) With a fresh profile install this addons:

https://addons.mozilla.org/en-US/firefox/addon/tab-mix-plus
https://addons.mozilla.org/en-US/firefox/addon/private-tab
https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak

2) Change extensions.privateTab.rememberClosedPrivateTabs to true
3) Restart firefox
4) Go to this page: https://github.com/Infocatcher
5) Open two tabs via ctrl+click on any link
6) Open two private tabs
7) Go to any private tab and press ctrl+F
8) Close tab
9.a) Press ctrl+shift+t --> error console shows "TypeError: cyclic object value"
9.b) Rigth-click on tab and go to "close tab list" --> List is empty and error console shows "TypeError: cyclic object value"
![sin titulo](https://cloud.githubusercontent.com/assets/4955944/11974988/887c9ad4-a969-11e5-9f89-92bba848bdce.png)

**Comment by Infocatcher** [comment]
Looks fixed for me after d526f93dff805d35139056e02095e359b7f191e4 commit.
Oh, now required xpinstall.signatures.required = false to test anything not signed. :(

**Comment by sdavidg** [comment]
Works perfect, thanks
