### ISSUE TITLE
nsISimpleContentPolicy issue

### ISSUE THREAD

**Issue by belaviyo** [Infocatcher/Private_Tab#205]
I am using [nsISimpleContentPolicy](https://github.com/mozilla/gecko-dev/blob/master/dom/base/nsISimpleContentPolicy.idl) to block some network resources in my extension.

```javascript
var {isPrivate} = require('sdk/private-browsing');
var policy = new Class({
  extends: Unknown,
  interfaces: ['nsISimpleContentPolicy'],
  shouldLoad: function (aContentType, aContentLocation, aRequestOrigin, aTopFrameElement, aIsTopLevel, aMimeTypeGuess, aExtra, aRequestPrincipal) {
    console.error(isPrivate(aTopFrameElement)) // <<<<<<<<
    return Ci.nsIContentPolicy.ACCEPT;
  },
  shouldProcess: () => Ci.nsIContentPolicy.ACCEPT
});
(function (factory) {
  categoryManager.addCategoryEntry('simple-content-policy', factory.contract, factory.contract, false, true);
  unload.when(() => categoryManager.deleteCategoryEntry('simple-content-policy', factory.contract, false));
  });
})(new Factory({
  Component:   policy,
  contract:    '@myaddon/simpletestpolicy;1',
  description: 'Blocks Some Resources'
}));
```

If I open a private window, the `isPrivate(aTopFrameElement)` returns `true` for all requests initiated from the private window as the `aTopFrameElement` is in the context of the private mode. However, if requests are from a private tab, `isPrivate(aTopFrameElement)` returns `false`. 

Any idea how to fix this?

**Comment by Infocatcher** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIContentPolicy#shouldLoad%28%29
> aContext
    The nsIDOMNode or nsIDOMWindow that initiated the request, or something that can QueryInterface() to one of those; can be null if inapplicable.

May be `aTopFrameElement` refers to topmost browser window, that is actually non-private.
You can try something like
```js
if(
	aTopFrameElement instanceof Ci.nsIDOMChromeWindow
	&& "gBrowser" in aTopFrameElement
) {
	var gBrowser = aTopFrameElement.gBrowser;
	var contentWindow = gBrowser.contentWindow || gBrowser.contentWindowAsCPOW;
	console.error(isPrivate(contentWindow));
}
```

**Comment by Infocatcher** [comment]
Also may be it's possible to ask `aRequestOrigin` about `Ci.nsILoadContext`.
Something like
```js
aRequestOrigin.loadGroup.notificationCallbacks
	.getInterface(Ci.nsILoadContext);
```
And then use `nsILoadContext.usePrivateBrowsing`.

**Comment by belaviyo** [comment]
It turned out `aTopFrameElement` is the actual XUL browser element. So I needed to dive into `aTopFrameElement.contentWindow` and then the `isPrivate` can detect the privacy context just fine.

Thanks for the help.
