### ISSUE TITLE
[e10s] Get rid "unsafe CPOW usage", this raise an error in Firefox 47.0a1+

### ISSUE THREAD

**Issue by Infocatcher** [Infocatcher/Private_Tab#208]
So, we can't use PrivateBrowsingUtils.isWindowPrivate(gBrowser.contentWindowAsCPOW) anymore...

**Comment by charlesmilette** [comment]
I also found something else:
`12:37:20,473 Only internal code is allowed to set the usePrivateBrowsing attribute bootstrap.js:3557:2`
Trigerred when opening a new private tab.

**Comment by Infocatcher** [comment]
This warning exists for years... and accessing to `usePrivateBrowsing` attribute is the only way to make tab private.
Briefly described here: https://addons.mozilla.org/addon/private-tab/#developer-comments

**Comment by charlesmilette** [comment]
Ah. Okay

**Comment by charlesmilette** [comment]
I got these log entries when disabling and renabling the addon (latest stable), which is totally broken in my Nightly (up-to-date).
```
12:50:01,432 1454349001432	addons.xpi	WARN	Add-on privateTab@infocatcher is missing bootstrap method shutdown
12:50:01,434 Could not read chrome manifest 'file:///C:/Program%20Files/Nightly/chrome.manifest'.
12:50:01,557 Use of nsIFile in content process is deprecated. Content.js:23:17
12:50:05,059 1454349005058	addons.xpi	WARN	Error loading bootstrap.js for privateTab@infocatcher: SyntaxError: missing ] after element list (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/Charles/AppData/Roaming/Mozilla/Firefox/Profiles/Charles/extensions/privateTab@infocatcher.xpi!/bootstrap.js:1569:22) JS Stack trace: @XPIProvider.jsm:4482:1 < this.XPIProvider.loadBootstrapScope@XPIProvider.jsm:4482:7 < this.XPIProvider.callBootstrapMethod@XPIProvider.jsm:4558:9 < this.XPIProvider.updateAddonDisabledState@XPIProvider.jsm:4726:13 < AddonWrapper.prototype.userDisabled@XPIProvider.jsm:7013:9 < gViewController.commands.cmd_enableItem.doCommand@extensions.js:1140:9 < gViewController.doCommand@extensions.js:1449:5 < initialize/<@extensions.js:104:5 < EventListener.handleEvent*initialize@extensions.js:103:3 < EventListener.handleEvent*@extensions.js:78:1
```

**Comment by Infocatcher** [comment]
> (latest stable)

With version 0.1.9?
This is due to already fixed  #203.

**Comment by charlesmilette** [comment]
Sorry, I completely forgot about Firefox's addon validation times. I thought it already made it.

**Comment by Infocatcher** [comment]
Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.1.9.2pre2-fx-sm.xpi">private_tab-0.1.9.2pre2-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/6ae4a746353516ece0f3f442d6e109a7cd9783ea">source code</a>)

**Comment by charlesmilette** [comment]
This beta version fixed all the problems that I had with Firefox Nightly.
