### ISSUE TITLE
Error: too much recursion 

### ISSUE THREAD

**Issue by JohnDDuncanIII** [Infocatcher/Private_Tab#214]
Sometimes, after a day or so of browsing, any new tab that I open (not just private tabs) will not work. They do not load completely, and if I attempt to click on them, nothing happens. I need to re-start the browser to get everything working again. The only line in the error console each time this happens (per-click on each broken tab) is:

Timestamp: 3/8/16, 8:04:25 PM
Error: too much recursion
Source File: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/John/Library/Application%20Support/SeaMonkey/Profiles/SeaMonkey.default/extensions/privateTab@infocatcher.xpi!/bootstrap.js
Line: 1194

This seems to point back to this add-on. SeaMonkey 2.39 on OS X 10.11.3

**Comment by Infocatcher** [comment]
Maybe following will fix this: df70dc267de8df5014a10838d7897572f8fe131a

Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.1.9.2pre-fx-sm.xpi">private_tab-0.1.9.2pre-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/df70dc267de8df5014a10838d7897572f8fe131a">source code</a>).
(but there is also many changes for upcoming multi-process mode in Firefox, so something may work wrong)

**Comment by JohnDDuncanIII** [comment]
Thanks. I will give it a try.

**Comment by Infocatcher** [comment]
Please reopen, if still happens for you.
