### ISSUE TITLE
[e10s] Favicons permanently disappear from tabs

### ISSUE THREAD

**Issue by modrzew** [Infocatcher/Private_Tab#224]
Private Tab seems to make favicons disappear from tabs. This doesn't happen immediately, but after browsing for a while (in my case, a couple days). There isn't even a default icon visible - after loading, spinner disappears and favicon never loads. Restarting browser, or even clearing moz_favicons table in places database doesn't help. Refreshing browser's profile helps, but only for a few days. Turning this addon off finally solved the issue.

Private Tab 0.1.9.1
Firefox 48 b1
Linux Mint 17.3

**Comment by Shaxine** [comment]
Same for me, but I'm on:
Firefox Nightly 50.0a1
elementaryOS 0.3.2 Freya (64-bit)

**Comment by tuxitop** [comment]
I'm also facing this problem on Firefox Aurora 50.0a2 with e10s enabled. seems like on a non e10s window favicons are shown with no problem, so It's probably a compatibility problem with e10s.

**Comment by Infocatcher** [comment]
I've added some fixes...

Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.1.9.2pre6-fx-sm.xpi">private_tab-0.1.9.2pre6-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/4339412903aaf95d5d987c80cc3bc631587e0c02">source code</a>).

**Comment by Shaxine** [comment]
It seems to be working fine for now, thanks.

I'm on Firefox Nightly 51.0a1 and I will let you know if anything goes south.

**Comment by tuxitop** [comment]
It's also fixed here. thank you!
