### ISSUE TITLE
Usage error in description

### ISSUE THREAD

**Issue by VLM1** [Infocatcher/Private_Tab#231]
Greetings! On your Firefox add-on page, in the description, you write: 

"Also you can create private bookmarks to always open some links in private tabs: just append “private:” before URL, example: private:https://addons.mozilla.org/"

The correct usage here is "prefix", not "append". To prefix is to put in front of or before; to append is to put behind or after. So instead of "append … before", please use "prefix 'private:' to". (It is also correct to say "prefix before" or "prefix preceding".  The error here lies in the use of "append", which always implies "after" or "following".)

Some use "prepend", which is lookalike jargon imitating "append". This is correct, as a matter of meaning/communication, but some dictionaries claim that it is jargon and not officially a word. :) Personally, I think it's a fine alternative.

Kind regards,

**Comment by Infocatcher** [comment]
Thanks, I've corrected description:
> Also you can create private bookmarks to always open some links in private tabs: just prefix “private:” before URL, example: private:https://addons.mozilla.org/

https://addons.mozilla.org/en-US/firefox/addon/private-tab/#addon-description

**Comment by VLM1** [comment]
Excellent, and thank you for listening!!!

 

Kind regards,
