### ISSUE TITLE
[e10s] Don't use CPOWs

### ISSUE THREAD

**Issue by Infocatcher** [Infocatcher/Private_Tab#234]
Also see #208 about "unsafe CPOW usage".

**Comment by Darmwind** [comment]
Hello,

I'm trying to get in contact with you but can't figure out a contact adress unfortunately. I would like to ask for a paid development. Kind of simplyfied version of your 'linked properties plus' plugin. Please respond to o.rafelsberger@gmx.at if you are interested.
I'd like to pay you for a downgraded pluglin based on your 'linked properties plus' plugin. It's all about security awareness.

Best regards,
Oliver
