### ISSUE TITLE
Ongoing downloads are cleared if last private tab is chrome://browser/content/places/places.xul

### ISSUE THREAD

**Issue by anewuser** [Infocatcher/Private_Tab#236]
1. Open `chrome://browser/content/places/places.xul` in a private tab
2. Start downloading this from a new private tab: http://scholar.princeton.edu/angelab/publications/super-large-pdf-100mb
3. Close the Princeton tab

Actual result: the download is removed.

Expected result: the download  should continue as there's still a private tab open, or there should be a warning about closing the last valid private tab.

Firefox 49 (not using e10s yet)
Linux

**Comment by Infocatcher** [comment]
Hmm, interesting, very similar to https://bugzilla.mozilla.org/show_bug.cgi?id=1329912 , but even without multi-process mode.

And with latest Private Tab I see
> [Private Tab] 09:30:234 last-pb-context-exited
[Private Tab] 09:30:249 Looks like wrong last-pb-context-exited (found opened private tab/window), ignore

But downloads are cleared from browser code...
