### ISSUE TITLE
Version 0.2.1 not working on a new profile (FF 50.1.0/Linux)

### ISSUE THREAD

**Issue by juozaspo** [Infocatcher/Private_Tab#240]
Private Tab v0.2.1 installed on a new profile is broken, there's no menu on tabs or elsewhere where it should be. No _extensions.privateTab.*_ in about:config either.
Browser console shows only a single warning about undefined variable while bootstrapping addon.

`1485004167185	addons.xpi	WARN	Exception running bootstrap method startup on privateTab@infocatcher: ReferenceError: _log is not defined (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/juozas/.mozilla/firefox/2qszt5fm.test7/extensions/privateTab@infocatcher.xpi!/bootstrap.js:4753:4) JS Stack trace: prefs.init@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/juozas/.mozilla/firefox/2qszt5fm.test7/extensions/privateTab@bootstrap.js:4753:4 < privateTab.init@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/juozas/.mozilla/firefox/2qszt5fm.test7/extensions/privateTab@bootstrap.js:37:3 < startup@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/juozas/.mozilla/firefox/2qszt5fm.test7/extensions/privateTab@bootstrap.js:24:2 < this.XPIProvider.callBootstrapMethod@XPIProvider.jsm:4800:9 < this.XPIProvider.startup@XPIProvider.jsm:2772:13 < callProvider@AddonManager.jsm:236:12 < _startProvider@AddonManager.jsm:788:5 < AddonManagerInternal.startup@AddonManager.jsm:972:9 < this.AddonManagerPrivate.startup@AddonManager.jsm:3016:5 < amManager.prototype.observe@addonManager.js:71:9`

Uninstalling gives another error:

`1485005139658	addons.xpi	WARN	Exception running bootstrap method shutdown on privateTab@infocatcher: TypeError: PrivateBrowsingUtils._privateTabOrigIsWindowPrivate is not a function (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/juozas/.mozilla/firefox/2qszt5fm.test7/extensions/privateTab@infocatcher.xpi!/bootstrap.js:4243:20) JS Stack trace: privateTab.isPrivateWindow@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/juozas/.mozilla/firefox/2qszt5fm.test7/extensions/privateTab@bootstrap.js:4243:20 < privateTab.askToClosePrivateTabs@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/juozas/.mozilla/firefox/2qszt5fm.test7/extensions/privateTab@bootstrap.js:1568:7 < privateTab.destroy@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/juozas/.mozilla/firefox/2qszt5fm.test7/extensions/privateTab@bootstrap.js:72:4 < shutdown@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/juozas/.mozilla/firefox/2qszt5fm.test7/extensions/privateTab@bootstrap.js:27:2 < this.XPIProvider.callBootstrapMethod@XPIProvider.jsm:4800:9 < this.XPIProvider.uninstallAddon@XPIProvider.jsm:5106:7 < AddonWrapper.prototype.uninstall@XPIProvider.jsm:7504:5 < uninstall@extensions.xml:1548:13 < oncommand@about:addons:1:1`

Work-around: Install version 0.2.0 or earlier, update to 0.2.1

Tested under Firefox 50.1.0, Xubuntu 16.10

**Comment by Infocatcher** [comment]
Oops, this is regression since fa7c9ab29f81607425a8926cac1fb68704226529 commit.
Corrected: 2e9f84dadba26e63f3eca6f60502314228b6e4c2
Thanks for report!

**Comment by Infocatcher** [comment]
https://github.com/Infocatcher/Private_Tab/releases/tag/0.2.1.1
https://addons.mozilla.org/addon/private-tab/versions/0.2.1.1 (in review queue for now)
