### ISSUE TITLE
Can't make an existing tab private anymore in Firefox 51+ with disabled multi-process mode

### ISSUE THREAD

**Issue by tgitnh** [Infocatcher/Private_Tab#241]
Today I changed from Firefox 51.0.1 32-bit to 64-bit (same add-ons, same computer). When I right-click on an existing tab, I can't activate "Private Tab" anymore. The tab closes and reopens, but it is not private.
However, opening links and bookmarks with right-click, "Open link in private tab" still works in FF 64-bit.

**Comment by Infocatcher** [comment]
Already fixed in development version: https://github.com/Infocatcher/Private_Tab/compare/5e1371ca5bf0bc1b44669604a3d4f5ddeff81e93...6f4aa342146dc2685218312095d66222b633b388
(affected Firefox 51+ with disabled multi-process mode)

**Comment by M0ns1gn0r** [comment]
The release v.0.2.1.2 is available on Github for 2 weeks, but on the Firefox Add-ons page it's still the version 0.2.1.1. When is it planned to publish the new one?

**Comment by Infocatcher** [comment]
Was uploaded on AMO right after GitHub...
For now:
> Queue Position: 21 of 184

![Private Tab on AMO](https://cloud.githubusercontent.com/assets/601488/22853248/67f55152-f062-11e6-8df2-4022a17e6295.png)

**Comment by anewuser** [comment]
This  may be closed now (and never affected me, by the way).
