### ISSUE TITLE
Define domains to open in private tabs. 

### ISSUE THREAD

**Issue by githubtefo** [Infocatcher/Private_Tab#250]
Hi!
Is there any way to always open certain domains as private tabs? For example, I'd be interesting in open always youtube.com/* directions in private mode from the address bar.
Thanks!

**Comment by anewuser** [comment]
Please close this issue.

Duplicate: https://github.com/Infocatcher/Private_Tab/issues/100

**Comment by githubtefo** [comment]
I'm sorry, I didn't find it. Closed.

**Comment by anewuser** [comment]
It's okay. I myself would like to have that feature. ;) But fortunately even the future of the basic extension is uncertain with all the upcoming changes Mozilla is doing/plans to do, and @Infocatcher basically develops this extension by himself. It'd be great if there was more help.
