### ISSUE TITLE
private:… URI may be opened only in new tab in Firefox 52+

### ISSUE THREAD

**Issue by Crazy-Clown** [Infocatcher/Private_Tab#251]
Not sure if this has been addressed or not, I have a bookmarked page on my bookmark toolbar within Firefox 52.0 32-bit, and the addon does not seem to function correctly just by simply clicking on the bookmark on the toolbar.  The tab is blank.  I have to right click the bookmarked site in the bookmark toolbar and click on "open in new tab" for the private: tab to be opened.

**Comment by anewuser** [comment]
After updating to 52, I can't use  `private:` at all in a regular tab with a site already loaded. It only works with blank tabs or tabs that are already private.

**Comment by Infocatcher** [comment]
See #237.
Was "fixed" from Firefox side and in Firefox 52+ was removed ability to change private state of already opened tab.
May be in this case is also possible trick with tab duplication (but it's harder to implement)...

**Comment by anewuser** [comment]
@Infocatcher  Please take a look at these resources https://blog.mozilla.org/addons/2017/03/09/office-hours-support-transitioning-porting-webextensions/ .

If you have the time, show the list of the problems affecting you everywhere, not just the bug tracker.

**Comment by Noitidart** [comment]
Hi there, thanks @anewuser  for the ping. So with my approach we leave Firefox behind. We will use native messaging to get the data we need from Firefox. Then we use native messaging to overlay our toolbar, or put the icon in the taskbar using this Electron API: https://electron.atom.io/docs/api/tray/

It will not have nearly the same feel and people will hesitate to download it as native messaging requires distributing an installer, which looks like the worst kind of spyware. Only people that really trust you will download and install it. Getting future users to trust you will be real hard if you aren't a popular brand name like Google or Microsoft.

**Comment by Noitidart** [comment]
So I looked more at your addon and you are offering a private tab. Electron is based on Chromium, so we can pop open a private new Chromium window, but that would defeat the purpose of this addon. :(

**Comment by Noitidart** [comment]
Well another thing we can do is making that private chromium window "LOOK" like a tab. Like when Firefox gets focus we can overlay Firefox with the tab. Tabs will not be accessible for focus via tab strip though, which still defeats the ease of having a "private tab". :(

**Comment by anewuser** [comment]
I see.  Your project isn't what we're aiming at. This has always been a native Firefox extension, and we just want Mozilla to stop replacing or dropping support for what @Infocatcher needs to make it work.

Hopefully those Mozilla employees/volunteers will be helpful (https://blog.mozilla.org/addons/2017/03/09/office-hours-support-transitioning-porting-webextensions/).

**Comment by woctezuma** [comment]
So I get that I cannot left-click on a private bookmark, I have to middle-click or right-click and "open in new tab".

**Comment by Infocatcher** [comment]
Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.2.2pre-fx-sm.xpi">private_tab-0.2.2pre-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/07c97aa2d62b25212c0b410fc478fa161a566d11">source code</a>).

Now will be used workaround with tab duplication.

**Comment by anewuser** [comment]
Can you upload the test version to AMO ([like uBlock Origin does](https://addons.mozilla.org/firefox/addon/ublock-origin/versions/beta))? I use the stable version of Firefox and can't install unverified extensions anymore.

**Comment by Infocatcher** [comment]
Signed version: https://addons.mozilla.org/addon/private-tab/versions/0.2.2pre

P.S. Also there is some hack to bypass signature check: https://www.ghacks.net/2016/08/14/override-firefox-add-on-signing-requirement/ (initially posted here: https://forum.mozilla-russia.org/viewtopic.php?pid=720001#p720001 -> http://fs5.directupload.net/images/160802/zkkixpzq.png)
Or more complex to fix issue with some extensions: https://forum.mozilla-russia.org/viewtopic.php?pid=734313#p734313

**Comment by anewuser** [comment]
Thank you for uploading it there. Not being able to use `private:` in regular tabs was driving me crazy. I have dozens of private bookmarks/custom searches with keywords.
