### ISSUE TITLE
Broken ability to open new private tab in Firefox 54.0a2+

### ISSUE THREAD

**Issue by afnkhn** [Infocatcher/Private_Tab#252]
This is what I got in Browser Console
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsILoadContext.usePrivateBrowsing]  bootstrap.js:3764

**Comment by Infocatcher** [comment]
After which action?
Also see #251 (+ #237).

**Comment by afnkhn** [comment]
on clicking button.

**Comment by Infocatcher** [comment]
Oh, I see.
As a temporary workaround: browser.newtab.preload = false (in about:config)

**Comment by Infocatcher** [comment]
Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.2.1.3pre2-fx-sm.xpi">private_tab-0.2.1.3pre2-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/56cc6b0943d2ddc428b3fb9d4e1b664c9b45fad7">source code</a>).

**Comment by afnkhn** [comment]
test version fixed the issue.

**Comment by Squall-Leonhart** [comment]
im fairly sure this change is incompatible with lazy tab loading.
