### ISSUE TITLE
RDM kill browser in private tab

### ISSUE THREAD

**Issue by dehghani-mehdi** [Infocatcher/Private_Tab#255]
Hello,

I'm using FF v52.0.2, also latest version of Private_Tab addon. sometimes when a page is open in Private tab (not private window), if I try to switch to mobile view (RDM I mean), Firefox doesn't response to anything & I have to close the main process. I tired in Private window multiple times & this didn't happen.

**Comment by anewuser** [comment]
You need to be more specific when you report bugs. What page caused the crash? I just tested the Responsive Design Mode both on example.org and Github in private tabs, and it worked as expected.

**Comment by dehghani-mehdi** [comment]
Excuse me @anewuser , are you a member/contributor of this project? you post an comment to almost all of issues. interesting.

As I mentioned in my post, I said __sometimes__.

**Comment by Infocatcher** [comment]
> are you a member/contributor of this project? you posted comment to almost all of issues. interesting.

Any user may help and any help is appreciated. :)

Responsive Design Mode works fine for me, but only with disabled multi-process mode.
And completely broken in multi-process mode.

**Comment by dehghani-mehdi** [comment]
@Infocatcher I enabled e10s, I'm not sure but I think if page has lot of JS code, RDM will be broken in Private Tab, but not always.
Notice that there is no issue with RDM for me in regular tabs

**Comment by dehghani-mehdi** [comment]
This issue still exists in FF 53, I removed your useful add-on today, also I think your add-on is not compatible enough with FF. (FF show strange behavior some times if one of tabs use PrivateTab)

**Comment by Infocatcher** [comment]
> also I think your add-on is not compatible enough with FF. (FF show strange behavior some times if one of tabs use PrivateTab)

More details, please.

And from https://addons.mozilla.org/addon/private-tab/reviews/866216/

<blockquote>
Almost unusable with FF +52
<br>It was great add-on, I wrote a review before, it was my #1 add-on, but not anymore, RDM (Responsive Design Mode) is not compatible with PrivateTab (there an issue about that in bugzilla). also seems like the developer doesn't support the add-on, (there is 58 open issues on Github)
<br>
<br>
<blockquote>
There is no way to fix anything, if Firefox developers takes backward incompatible changes in each release without working feedback. For example, see
<a href="https://github.com/Infocatcher/Private_Tab/issues/237#issuecomment-261311012">https://github.com/Infocatcher/Private_Tab/issues/237#issuecomment-261311012</a>
<br>
<br>Also it's not possible to handle bugs like a UI hangs from extension side (if extension do nothing during that hang). Sad, but true.
<br>
<br>About open issues: feel free to fix something or find someone to fix that for you, this is free and open source project.
<br>Also I'm still unable to reproduce your issue with disabled e10s mode.
</blockquote></blockquote>

**Comment by dehghani-mehdi** [comment]
Thanks for the response, you right, Firefox lost its way, it's hard to keep up to date the add-on with Firefox changes. (_and yes your code is open source, free & available to change/edit_)

BUT
I'm developer too man, I'm have not any open source project like you, but I think if you can not (not about your skills or ability) for any reason, at least warn the users about possibility issues about using your code. you did this for users, it's great, but respect them & their time.

Anyway I believe Mozilla is not in right way about Firefox (it's not good for you as add-on developer and people like me as FF users), today I remove your add-on, maybe tomorrow I decided to switch to Chrome.

I reported this issue because I like to let you know about existing problem, your idea and add-on is most useful idea about add-on (in my opinion). _I'm not fan of add-ons, but PrivateTab is great and useful_, and I wrote that review to let other people know about existing issue about your add-on to help them as well.

Thanks again ;)
