### ISSUE TITLE
Compatibility issue on latest Firefox Dev Edition

### ISSUE THREAD

**Issue by Wisdoom** [Infocatcher/Private_Tab#279]
Private Tab add on no longer compatible, I'm on Firefox Developer Edition v57.0b1 (64bit).

**Comment by notDavid** [comment]
It's now also no longer compatible with the Firefox **Beta** update channel... (currently 57.0b4)

**Comment by Cediddi** [comment]
I guess the development is being done in another repository https://github.com/Infocatcher/Private_Tab_WE

**Comment by Wisdoom** [comment]
You are right, the Private_Tab issue #254 (https://github.com/Infocatcher/Private_Tab/issues/254) mentioned that this was going to happen, so Infocatcher started the Private Tab WE (WebExtension) :)
